version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install yarn dependencies
          command: |
             yarn
      - run:
          name: Run typescript
          command: |
             yarn tsc
